// Re-imports files generated by the /proposer forms (or hand-written to the
// documented format) back into the form drafts: the path for a rubrique or a
// besoin received as a .yaml file (téléchargé, ou envoyé sur Discord) that
// someone else loads, finishes and sends. Tolerant on shape: accepts a single
// YAML object or a one-element list.
import type { Department } from '../config/departments'
import type { EditionDepartmentDraft, NeedDraft } from './compose'
import { loadYamlDocument } from './frontmatter'
import { departmentEntrySchema, needSchema } from './schemas'

function unwrap(text: string): unknown {
  let doc: unknown
  try {
    doc = loadYamlDocument(text)
  } catch {
    return null
  }
  return Array.isArray(doc) && doc.length === 1 ? doc[0] : doc
}

// A section file references images by src; the form thinks in repo file names
// (re-linked under the target edition's slug at compose time). External
// https:// images have no repo file to re-link, so they are not importable.
export function parseSectionImport(text: string): EditionDepartmentDraft | null {
  const parsed = departmentEntrySchema.safeParse(unwrap(text))
  if (!parsed.success) return null
  const section = parsed.data
  return {
    name: section.name as Department,
    notes: section.notes ?? '',
    done: section.done,
    in_progress: section.in_progress,
    next: section.next,
    help_wanted: section.help_wanted,
    images: section.images
      .filter((image) => image.src.startsWith('/'))
      .map((image) => ({
        name: decodeURIComponent(image.src.split('/').pop() ?? ''),
        caption: image.caption ?? '',
      }))
      .filter((image) => image.name !== ''),
  }
}

export function parseNeedImport(text: string): NeedDraft | null {
  const parsed = needSchema.safeParse(unwrap(text))
  if (!parsed.success) return null
  const need = parsed.data
  return {
    id: need.id,
    type: need.type,
    title: need.title,
    department: need.department as Department,
    description: need.description,
    skills: need.skills,
    time_estimate: need.time_estimate ?? '',
    contact: need.contact,
    // Imported needs go back to the board as open proposals.
    status: 'open',
    posted: need.posted.toISOString().slice(0, 10),
  }
}
