import { describe, expect, it } from 'vitest'
import { composeNeedYaml, composeSectionYaml } from './compose'
import { parseNeedImport, parseSectionImport } from './importYaml'

describe('parseSectionImport', () => {
  it('round-trips a file generated by the form back into a draft', () => {
    const yaml = composeSectionYaml('2026-q3', {
      name: 'Ops & Nav',
      notes: 'Le mot du trimestre.',
      done: ['Cartes LFPG publiées'],
      in_progress: [],
      next: ['Doc LFLL'],
      help_wanted: [],
      images: [{ name: 'secteurs LFMM.png', caption: 'Découpage' }],
    })
    const draft = parseSectionImport(yaml)!
    expect(draft.name).toBe('Ops & Nav')
    expect(draft.notes).toBe('Le mot du trimestre.')
    expect(draft.done).toEqual(['Cartes LFPG publiées'])
    expect(draft.next).toEqual(['Doc LFLL'])
    // The repo src is re-linked by file name (slug re-applied at compose time).
    expect(draft.images).toEqual([{ name: 'secteurs LFMM.png', caption: 'Découpage' }])
  })

  it('accepts a one-element list and drops non-repo images', () => {
    const draft = parseSectionImport(
      ['- name: "Events"', '  done: ["Real Ops"]', '  images:', '    - src: "https://exemple.org/x.png"'].join('\n'),
    )!
    expect(draft.name).toBe('Events')
    expect(draft.images).toEqual([])
  })

  it('rejects unknown teams and non-section files', () => {
    expect(parseSectionImport('name: "Ancienne Team"\ndone: ["x"]')).toBeNull()
    expect(parseSectionImport('just some text')).toBeNull()
    expect(parseSectionImport(': not yaml : [')).toBeNull()
  })
})

describe('parseNeedImport', () => {
  it('round-trips a generated need file into a draft', () => {
    const yaml = composeNeedYaml({
      id: 'ops-nav-relecture',
      type: 'ponctuel',
      title: 'Relecture LFPG',
      department: 'Ops & Nav',
      description: 'Relire la doc.',
      skills: ['Rigueur'],
      time_estimate: '2–3 h',
      contact: 'Ticket Membership',
      status: 'open',
      posted: '2026-08-01',
    })
    const draft = parseNeedImport(yaml)!
    expect(draft.id).toBe('ops-nav-relecture')
    expect(draft.department).toBe('Ops & Nav')
    expect(draft.posted).toBe('2026-08-01')
    expect(draft.status).toBe('open')
    expect(draft.time_estimate).toBe('2–3 h')
  })

  it('re-opens filled needs and rejects malformed files', () => {
    const filled = parseNeedImport(
      [
        '- id: "x-y"',
        '  type: "poste"',
        '  title: "T"',
        '  department: "Digital"',
        '  description: "D"',
        '  contact: "C"',
        '  status: "filled"',
        '  posted: 2026-08-01',
        '  filled_at: 2026-08-15',
      ].join('\n'),
    )!
    expect(filled.status).toBe('open')
    expect(parseNeedImport('id: "missing-everything"')).toBeNull()
  })
})
