name: Training Department
notes: |-
  Nous avons le plaisir d’annoncer la beta de la plateforme de formation !
  L’accès a la plateforme est donné progressivement aux élèves en cours de formation puis a ceux qui entreront en formation.

  Vous pouvez déjà vous y connecter, votre page d’accueil vous affiche votre activité récente et le respect des activity requirements.
  Si vous êtes en formation et que la session proposée par la plateforme est incorrecte, veuillez ne pas proposer de disponibilités nous reviendrons vers vous !
done:
  - Entrée en formation de 3 nouveaux contrôleurs (1 n’a pas répondu, 1 est en cours)
  - 2 CPT S2 réussis
  - Refonte du cursus S3, passage en CBTA
  - Entrée en beta de la plateforme de formation in-house
  - 3 nouveaux mentors
  - 8 qualifications Tier 1
  - 7 nouveaux ATC au roster
  - 1 fast track S3
  - 3 transferts
  - 2 retour au roster
in_progress:
  - Transfert du contenu de learn.vatsim.fr vers la plateforme de formation
  - Mise en place de positions Tour ouvrables avec un grade S1
  - Amélioration de l’efficience des processus du département
  - 3 ATC visiteurs
  - 2 transferts
  - 7 élèves S3 (dont 3 solos)
  - 14 élèves S2 (dont XX solos)
  - 2 élèves S1
next:
  - Refonte du cursus C1
  - Passage en CBTA des cursus S1 et S2
